---
title: "RSA_salt"
author: "Zulema Carracedo Lorenzo"
date: "2026-01-18"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#data management
library(dplyr)
library(tidyr)
library(tidyverse)
library(stringr)
library(readxl)
library(flextable)

#statistics
library(multcompView)
library(vegan)
library(pairwiseAdonis)
library(emmeans)
library(DHARMa) #for simmulate residuals
library(glmmTMB) #for glmm
library(car)

#plots
library(ggplot2)
library(ggpattern)
library(rempsyc) #for tables
library(fitdistrplus)

# packages needed for Cohen's D
library(effsize)  
library(effectsize)
library(lsr)

#for tables
library(flextable)
library(officer)
library(car)
library(emmeans)
library(multcomp)

```


```{r}

#Import data

#RSA
RSA <- read.csv("./6_extra/Salt_stress/data/data.csv", sep = ";", header = TRUE)
RSA <- as.data.frame(RSA)

str(RSA)

RSA[,4:6] <- lapply(RSA[,4:6], as.numeric)

#Biomass
biomass <- read.csv("./6_extra/Salt_stress/data/biomass.csv", sep = ";", header = TRUE)

#fix numbers with "," and convert to numberic
biomass[, 3:5] <- lapply(biomass[, 3:5], function(x) {
  x <- gsub(",", ".", x)    # convert decimal comma to dot
  as.numeric(x)
})

str(biomass)
#convert seedling biomass from g to mg
biomass <- biomass %>%
  mutate(seedling_FW_mg = seedling_FW_g * 1000)

```



#Arrange data for plots

```{r}

RSA$Treatment <- factor(RSA$Treatment, levels=c("Salt_mock", "Salt_WCS417"))
biomass$Treatment <- factor(biomass$Treatment, levels=c("mock", "PsWCS417"))
```

#colors

```{r}
control <- #76CFE8
WCS417 <- #C9DC53

```

#Plots

```{r}
##Primary root length

ggplot(RSA, aes(x = Treatment, y = PRL, fill = Treatment)) +
  scale_fill_manual(name = "Treatment", values = c("#76CFE8", "#C9DC53")) +
  ylab("Primary root length (cm)") +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitterdodge(), alpha=0.5, size = 2) + 
  theme_bw(18) + 
  theme(legend.position="top") +
  guides(fill= FALSE) +
  theme(
        axis.title.x = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()) +
  scale_y_continuous(limits = c(0, NA))   # Force y-axis to start at 0
  


mapply(function(x)
  ggsave(
  plot = last_plot(),
  filename =x,
  path = "./6_extra/Salt_stress/results",
  scale = 1.8,
  width = 150,
  height = 100,
  units = "mm",
  dpi = 300),
x=c("Fig_SX_A_primary_length.svg","Fig_SX_A_primary_length.png"))


##lateral root count

ggplot(RSA, aes(x = Treatment, y = LRN, fill = Treatment)) +
  scale_fill_manual(name = "treatment", values = c("#76CFE8", "#C9DC53")) +
  ylab("Lateral root count") +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitterdodge(), alpha=0.5, size = 2) + 
  theme_bw(18) + 
  theme(legend.position="top") +
  guides(fill= FALSE) +
  theme(
        axis.title.x = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()) +
  scale_y_continuous(limits = c(0, NA))   # Force y-axis to start at 0



mapply(function(x)
  ggsave(
  plot = last_plot(),
  filename =x,
  path = "./6_extra/Salt_stress/results",
  scale = 1.8,
  width = 150,
  height = 100,
  units = "mm",
  dpi = 300),
x=c("Fig_SX_B_lateral_count.svg","Fig_SX_B_lateral_count.png"))


##seedling FW

ggplot(biomass, aes(x = Treatment, y = seedling_FW_mg, fill = Treatment)) +
  scale_fill_manual(name = "treatment", values = c("#76CFE8", "#C9DC53")) +
  ylab("Total fresh weight (mg)") +
  geom_boxplot(outlier.shape = NA) +
  geom_point(position = position_jitterdodge(), alpha=0.5, size = 2) + 
  theme_bw(18) + 
  theme(legend.position="top") +
  guides(fill= FALSE) +
  theme(
        axis.title.x = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank()) +
  scale_y_continuous(limits = c(0, NA))   # Force y-axis to start at 0



mapply(function(x)
  ggsave(
  plot = last_plot(),
  filename =x,
  path = "./6_extra/Salt_stress/results",
  scale = 1.8,
  width = 150,
  height = 100,
  units = "mm",
  dpi = 300),
x=c("Fig_SX_C_FW.svg","Fig_SX_C_FW.png"))
```

#Stats
```{r}
#primary length

#check normality
shapiro.test(RSA$PRL)#normal

#check homogenity of variance
leveneTest(PRL ~ Treatment, data = RSA)

#we can use t-test
t.test(PRL ~ Treatment, data = RSA) #p-value = 0.683 not significant

#Lateral root count
#check normality
shapiro.test(RSA$LRN) #normal

#check homogenity of variance
leveneTest(LRN ~ Treatment, data = RSA)

#we can use t-test
t.test(LRN ~ Treatment, data = RSA) #p-value = 6.911e-6 ***

#Seedling FW
#check normality
shapiro.test(biomass$seedling_FW_mg) #not normal

#check homogenity of variance
leveneTest(seedling_FW_mg ~ Treatment, data = biomass)

#we can use wilcoxon
wilcox.test(seedling_FW_mg ~ Treatment, data = biomass) #p-value = 4.999e-08 ***
```

